import "./globals.css";
import Link from 'next/link';
import Navbar from './components/Navbar';

export const metadata = {
  title: "First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex">
        <div flex min-h-screen>
          <Navbar />
          <main className="flex-grow">{children}</main>
        </div>

      </body>
    </html>
  );
}