import "./globals.css";
import Link from 'next/link';
import Navbar from './components/Navbar';
import AppShell from './components/AppShell';

export const metadata = {
  title: "First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>

            <AppShell >{children}</AppShell>


        </body>
    </html>
  );
}